#!/bin/bash
# Minimal Bash 3-compatible wg-quick for the macOS GitHub runner.
# The upstream script requires Bash 4 for associative arrays, while the
# runner's /bin/bash is Apple's Bash 3. This script handles the WARP profile
# generated by wgcf without a package manager or a shell upgrade.
set -e

WG=${WG_BIN:-wg}
WGGO=${WG_QUICK_USERSPACE_IMPLEMENTATION:-wireguard-go}
STATE_DIR=/var/run/wireguard
NAME=wgcf
NAME_FILE="$STATE_DIR/$NAME.name"
SOCKET="$STATE_DIR/$NAME.sock"
ENDPOINT_FILE="$STATE_DIR/$NAME.endpoint"

fail() { echo "wg-quick: $*" >&2; exit 1; }
field() {
  awk -F= -v key="$1" '$1 ~ "^[[:space:]]*" key "[[:space:]]*$" { sub(/^[[:space:]]+/, "", $2); sub(/[[:space:]]+$/, "", $2); gsub(/,/, " ", $2); print $2; exit }' "$2"
}

[ "$(id -u)" -eq 0 ] || fail "must run as root"
[ "$#" -eq 2 ] || fail "usage: wg-quick {up|down} PROFILE"
ACTION=$1
PROFILE=$2
[ -f "$PROFILE" ] || fail "profile does not exist: $PROFILE"

endpoint_host() {
  local endpoint host
  endpoint=$(field Endpoint "$PROFILE")
  host=${endpoint%:*}
  host=${host#[}
  host=${host%]}
  printf '%s' "$host"
}

endpoint_ip() {
  local host ip
  host=$(endpoint_host)
  ip=$(route -n get -inet "$host" 2>/dev/null | awk '/destination:/{print $2; exit}')
  case "$ip" in
    ''|default|*[!0-9.]) ip=$(dig +short A "$host" 2>/dev/null | awk '/^[0-9.]+$/{print; exit}') ;;
  esac
  case "$ip" in
    ''|default|*[!0-9.]) ip=$(dscacheutil -q host -a name "$host" 2>/dev/null | awk '/^ip_address:/{print $2; exit}') ;;
  esac
  printf '%s' "$ip"
}

up() {
  mkdir -p "$STATE_DIR"
  if [ -e "$NAME_FILE" ]; then down || true; fi

  export WG_TUN_NAME_FILE="$NAME_FILE"
  "$WGGO" utun
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    [ -s "$NAME_FILE" ] && break
    sleep 1
  done
  if [ ! -s "$NAME_FILE" ]; then
    "$WGGO" down "$NAME" >/dev/null 2>&1 || true
    fail "wireguard-go did not create an interface"
  fi
  iface=$(cat "$NAME_FILE")
  [ -n "$iface" ] || fail "empty WireGuard interface name"

  # Keep only wg(8) settings; Address/DNS/MTU are handled below.
  conf=$(mktemp)
  awk 'BEGIN { section="" }
    /^\[/{ section=$0 }
    section == "[Interface]" && $0 ~ /^[[:space:]]*(Address|DNS|MTU|Table|SaveConfig)[[:space:]]*=/ { next }
    { print }' "$PROFILE" > "$conf"
  if ! "$WG" setconf "$iface" "$conf"; then
    rm -f "$conf"
    "$WGGO" down "$iface" >/dev/null 2>&1 || true
    rm -f "$NAME_FILE"
    fail "WireGuard configuration failed"
  fi
  rm -f "$conf"

  ifconfig "$iface" up
  addresses=$(field Address "$PROFILE")
  for address in $addresses; do
    case "$address" in
      *:*) ifconfig "$iface" inet6 "$address" alias ;;
      *) base=${address%/*}; ifconfig "$iface" inet "$base" "$base" alias ;;
    esac
  done
  mtu=$(field MTU "$PROFILE")
  [ -z "$mtu" ] || ifconfig "$iface" mtu "$mtu"

  # Keep the WireGuard endpoint reachable outside the two default routes.
  ip=$(endpoint_ip)
  gateway=$(route -n get default 2>/dev/null | awk '/gateway:/{print $2; exit}')
  if [ -n "$ip" ] && [ -n "$gateway" ]; then
    route -q -n add -inet "$ip" "$gateway" >/dev/null 2>&1 || true
    printf '%s\n' "$ip" > "$ENDPOINT_FILE"
  fi

  # wgcf allows all IPv4/IPv6 traffic. Split default routes avoid replacing
  # the original default route and work with the macOS utun interface.
  route -q -n add -inet 0.0.0.0/1 -interface "$iface"
  route -q -n add -inet 128.0.0.0/1 -interface "$iface"
  route -q -n add -inet6 ::/1 -interface "$iface" || true
  route -q -n add -inet6 8000::/1 -interface "$iface" || true
  echo "wg-quick: WARP interface $iface is up"
}

down() {
  [ -s "$NAME_FILE" ] || exit 0
  iface=$(cat "$NAME_FILE")
  route -q -n delete -inet 0.0.0.0/1 >/dev/null 2>&1 || true
  route -q -n delete -inet 128.0.0.0/1 >/dev/null 2>&1 || true
  route -q -n delete -inet6 ::/1 >/dev/null 2>&1 || true
  route -q -n delete -inet6 8000::/1 >/dev/null 2>&1 || true
  if [ -s "$ENDPOINT_FILE" ]; then
    route -q -n delete -inet "$(cat "$ENDPOINT_FILE")" >/dev/null 2>&1 || true
  fi
  ifconfig "$iface" down >/dev/null 2>&1 || true
  rm -f "$SOCKET" "$NAME_FILE" "$ENDPOINT_FILE"
  echo "wg-quick: WARP interface is down"
}

case "$ACTION" in
  up) up ;;
  down) down ;;
  *) fail "unknown action: $ACTION" ;;
esac
